baseurl: ''
title: "Оксана Коновалова — клинический психолог, доказательные протоколы КПТ и ДБТ"
description: "Трихотилломания, Когнитивно-поведенческая терапия (КПТ), Диалектическая поведенческая терапия (ДБТ), Терапия принятия и ответственности (ACT), Обсессивно-компульсивные расстройства, депрессивные расстройства"
url: "https://oksana-konovalova.ru"
permalink: /:slug.html
image: /assets/images/main.jpg\
keywords: Тревожные расстройства и панические атаки, Депрессии, Обсессивно-компульсивное расстройство (ОКР), Посттравматическое стрессовое расстройство (ПТСР), Бессонница (инсомния), Трихотилломания и дерматилломания, Нарушения пищевого поведения, Эмоциональная нестабильность и ПРЛ
locale: ru_RU

author:
  image: /assets/images/main.jpg
  name: Оксана Коновалова
  about: Когнитивно-поведенческий психотерапевт, клинический психолог, основатель проекта TTM-HELP

footer_title: ИП Коновалова Оксана Валерьевна ИНН 645293010504
sass:
  indentWidth: 4
  precision: 10
  style: compressed # possible values: nested expanded compact compressed
  sourcemap: always

jekyll-minifier:
  compress_css: false

jekyll_seo_tag:
  generator: false

plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-image-size
  - jekyll-seo-tag

exclude:
  - "*.iml"
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
